greeting:
  image: sdoroshenko/greeting
  replicaCount: 1

image:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
  externalDebugPort: 5005
  internalDebugPort: 5005